name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      name: Checkout code


    - uses: docker/build-push-action@v2
      name: Build Docker image
      with:
        context: ./app
        push: true
        tags: burntroll/github-runner:1.0

    - name: Run Docker container
      run: |
        docker-compose up -d
      working-directory: ./app


#stages:
#  - build
#  - deploy

#create_images:
#  stage: build
#  tags:
#    - Linux
#  script:
#    - docker build -t burntroll/github-runner:1.0 app/.
#    - docker push burntroll/github-runner:1.0

#run_images:
#  stage: deploy
#  needs:
#    - create_images
#  tags:
#    - Linux
#  script:
#    - docker run -dti --name webserver -p 80:80 burntroll/github-runner:1.0

