name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      name: Checkout code


    - uses: docker/build-push-action@v3
      name: Build Docker image
      with:
        context: ./app
        push: true
        tags: burntroll/github-runner:1.0
        load: false
        no-cache: false
        pull: false
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run Docker container
      run: docker build -t burntroll/github-runner:1.0 .
      working-directory: ./app

    - name: Push Docker container
      run: docker push burntroll/github-runner:1.0
      working-directory: ./app     

  run-container:
    runs-on: self-hosted
    needs:
      - build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker container
        run: |
          docker run -dti --name webserver -p 80:80 burntroll/github-runner:1.0